language: node_js

sudo: required

node_js:
  - v10.8.0

cache:
  directories:
    - node_modules

notifications:
  email:
    recipients:
      - williamstowersdev@gmail.com
    on_success: never
    on_failure: always

before_install:
  - npm install -g pm2

script:
  - npm install
  - npm run lint
  - npm run build
  - npm link
  - npm run kinesisLocalStart
  - nqr -a examples/kinesis.yml -l /home/travis/build/williamsdevaccount/enqueuer-plugin-kinesis && sleep 10
  - npm run kinesisLocalStop